# Generated by Django 5.2.5 on 2025-08-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats_app", "0003_apicalllog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="in_group",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="player_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="PlayerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                (
                    "group_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stats_app.groupmember",
                    ),
                ),
            ],
        ),
    ]
