# Generated by Django 5.2.5 on 2025-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stats_app",
            "0004_groupmember_in_group_alter_groupmember_player_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerhistory",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
