# Generated by Django 5.2.5 on 2025-08-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_app.groupmember')),
            ],
        ),
    ]
