# Generated by Django 5.2.5 on 2025-08-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats_app", "0002_playerstatscache"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="playerstatscache",
            old_name="timestamp",
            new_name="last_updated",
        ),
        migrations.AlterField(
            model_name="playerstatscache",
            name="group_member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="stats_app.groupmember"
            ),
        ),
    ]
